wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
cost_gamma:
  desc: null
  value: 0.99
cost_lim:
  desc: null
  value: 10
cpu:
  desc: null
  value: 2
epochs:
  desc: null
  value: 50
gamma:
  desc: null
  value: 0.98
hid:
  desc: null
  value: 128
l:
  desc: null
  value: 2
lam:
  desc: null
  value: 0.995
seed:
  desc: null
  value: 0
steps:
  desc: null
  value: 4000
