wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
cost_gamma:
  desc: null
  value: 0.9984569622307674
cost_lim:
  desc: null
  value: 20
epochs:
  desc: null
  value: 100
gamma:
  desc: null
  value: 0.985962984798709
optim_mode:
  desc: null
  value: adam
seed:
  desc: null
  value: 99
