wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
cost_gamma:
  desc: null
  value: 0.98
cost_lim:
  desc: null
  value: 10
cpu:
  desc: null
  value: 2
epochs:
  desc: null
  value: 100
gamma:
  desc: null
  value: 0.99
hid:
  desc: null
  value: 128
l:
  desc: null
  value: 1
penalty_lr:
  desc: null
  value: 0.0072988602617487085
seed:
  desc: null
  value: 999
steps:
  desc: null
  value: 4000
