wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
cost_gamma:
  desc: null
  value: 0.9822767941866302
cost_lim:
  desc: null
  value: 5
epochs:
  desc: null
  value: 500
gamma:
  desc: null
  value: 0.9926620590511984
optim_mode:
  desc: null
  value: adabelief
seed:
  desc: null
  value: 0
