wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
cost_gamma:
  desc: null
  value: 0.9985215732705961
cost_lim:
  desc: null
  value: 0
epochs:
  desc: null
  value: 1000
gamma:
  desc: null
  value: 0.9842886559455111
optim_mode:
  desc: null
  value: lbgfs
seed:
  desc: null
  value: 99
